image: node:latest

stages:
    - installing_browsers
    - npms
    - tests
    
installing_browsers:
    stage: installing_browsers
    script:
        - echo "installing browsers on docker instance"
        - wget -q -O — https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
        - echo ‘deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main’ | tee /etc/apt/sources.list.d/google-chrome.list
        - apt-get update
        - apt-get install google-chrome-stable -y
        
npms:
    stage: npms
    script:
        - npm install -g mocha selenium-webdriver chromedriver geckodriver
        - npm install
    cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
    artifacts:
        paths:
            - node_modules/
            
tests:
    stage: tests
    script:
        - mocha tests/

    