image: node:latest

stages:
    - installing_browsers
    - npms
    - tests
    
installing_browsers:
    stage: installing_browsers
    script:
        - echo "installing browsers on docker instance"
        - apt-get update
        - apt-get install google-chrome-stable -y
        
npms:
    stage: npms
    script:
        - npm install -g mocha selenium-browser chromedriver geckodriver
        - npm install
            
tests:
    stage: tests
    script:
        - mocha tests/