image: node:latest

stages:
    - installing_browsers
    - npms
    - tests
    
installing_browsers:
    stage: installing_browsers
    script:
        - cat /etc/os-release
        # - echo "installing browsers on docker instance"
        # - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        # - dpkg -i google-chrome-stable_current_amd64.deb
        # - apt-get update
        # - apt-get install google-chrome-stable -y
        
npms:
    stage: npms
    script:
        - npm install -g mocha
        - npm install
    cache:
        paths:
            - node_modules/
            
tests:
    stage: tests
    script:
        - mocha tests/
